### ISSUE TITLE
Read Access Violation

### ISSUE THREAD

**Issue by SmeetSabalpara** [adamhlt/PE-Explorer#2]
I am getting "Read Access Violation" exception whenever I try to access any element of NTHeader.

**Comment by adamhlt** [comment]
~~Hi, can you give me more informations ? Which type of file are you analysing, etc...~~

**Comment by adamhlt** [comment]
Everyting should work now, I add support to build the explorer in x64.

**Comment by SmeetSabalpara** [comment]
Yes, it worked! Could you please explain to me in some detail what you did? I've been trying to solve this issue for quite a few days.

**Comment by adamhlt** [comment]
@SmeetSabalpara, I change every cast of DWORD to DWORD_PTR, this allow build in x64, else when you do an allocation a DWORD is not large enough to store the pointer (in x64) and you need DWORD to do math on pointer.

**Comment by SmeetSabalpara** [comment]
Oh, I see! Thank you so much. Your GitHub profile is greatly appreciated🫡

**Comment by adamhlt** [comment]
Thank you, I really appreciate it ❤️
