### ISSUE TITLE
error in 'EXPORTED FUNCTIONS'

### ISSUE THREAD

**Issue by gashasbi** [adamhlt/PE-Explorer#3]
Hello.
when the program tries to display the exported functions, it encounters a problem. I think in the GetExports function, if you change the casting to DWORD*, the problem will be resolved.

Line: 370
Replace this:
`const auto pArrayOfFunctionsNames = (DWORD_PTR*)(dRawOffset + (pImageExportDirectory->AddressOfNames - pImageExportSection->VirtualAddress));`

with this:
`const auto pArrayOfFunctionsNames = (DWORD*)(dRawOffset + (pImageExportDirectory->AddressOfNames - pImageExportSection->VirtualAddress));`

thanks

**Comment by adamhlt** [comment]
Thanks you for reporting the problem, I change all cast from DWORD* to DWORD_PTR* for a quick patch because nobody read the readme and was trying to compile it as x64 binary. I will fix that.

**Comment by gashasbi** [comment]
Alright. thank you! :)

**Comment by adamhlt** [comment]
Thanks, I just fix the problem thanks to you.
